import"./assets/styles-LHsz4fpJ.js";import{a as i,i as T}from"./assets/vendor-Cbhu4xvy.js";const R="https://dummyjson.com",n={CATEGORIES:"/products/category-list",ALL_PRODUCTS:"/products?limit=12&skip=",ONE_PRODUCT:"/products/",QUERY_PRODUCT:"/products/search?q=",PER_PAGE:"&limit=12&skip="},d=12;i.defaults.baseURL=R;async function q(){const{data:t}=await i(`${n.CATEGORIES}`);return t}async function $(t){const{data:o}=await i(`${n.ALL_PRODUCTS}${(t-1)*d}`);return o}async function O(t){const{data:o}=await i(`${n.ONE_PRODUCT}${t}`);return o}async function S(t,o){const{data:r}=await i(`${n.QUERY_PRODUCT}${t}${n.PER_PAGE}${(o-1)*d}`);return r}const e={categoriesList:document.querySelector("ul.categories"),productList:document.querySelector("ul.products"),loadMoreBtn:document.querySelector(".load-more-btn"),modal:document.querySelector(".modal"),modalBackdrop:document.querySelector(".js-modal-backdrop"),modalProduct:document.querySelector(".modal-product"),modalClose:document.querySelector(".modal__close-btn"),formSearch:document.querySelector(".search-form"),notFoundDiv:document.querySelector(".not-found"),clearBtn:document.querySelector(".search-form__btn-clear")};function D(t){const o=t.map(r=>`<li class="categories__item">
   <button class="categories__btn" type="button">${r}</button>
 </li>
`).join("");e.categoriesList.innerHTML=o}function L(t){const o=t.map(({id:r,thumbnail:p,title:m,brand:_,category:f,price:y,description:g})=>`<li class="products__item" data-id="${r}">
    <img class="products__image" src="${p}" alt="${g}"/>
    <p class="products__title">${m}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${_}</span></p>
    <p class="products__category">Category: ${f}</p>
    <p class="products__price">Price: ${y}$</p>
 </li>`).join("");e.productList.insertAdjacentHTML("beforeend",o)}function F({thumbnail:t,title:o,shippingInformation:r,price:p,description:m,tags:_,returnPolicy:f}){const y=`<img class="modal-product__img" src="${t}" alt="${o}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${o}</p>
        <ul class="modal-product__tags">${_.map(g=>`<li>${g}</li>`).join("")}</ul>
        <p class="modal-product__description">${m}</p>
        <p class="modal-product__shipping-information">Shipping: ${r}</p>
        <p class="modal-product__return-policy">Return Policy: ${f}</p>
        <p class="modal-product__price">Price: ${p}$</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`;e.modalProduct.innerHTML=y}const E={timeout:5e3,theme:"dark",messageColor:"white",iconColor:"#FFFFFF",closeOnClick:!0,backgroundColor:"#ef4040",position:"topCenter"};function A(){const t=document.querySelector(".categories__btn");t&&t.classList.add("categories__btn--active")}function l(t){console.log(t),E.message=t.message,T.show(E)}function b(){e.productList.innerHTML=""}function P(t,o){if(t<o)U(),e.loadMoreBtn.removeEventListener("click",h),e.loadMoreBtn.addEventListener("click",h);else throw e.loadMoreBtn.removeEventListener("click",h),k(),C(),new Error("No more products to load")}function U(){e.loadMoreBtn.classList.remove("is-hidden"),C()}function k(){e.loadMoreBtn.classList.add("is-hidden")}function N(){e.notFoundDiv.classList.add("not-found--visible"),k()}function C(){e.notFoundDiv.classList.remove("not-found--visible")}function j(){e.modal.classList.add("modal--is-open"),e.modalClose.addEventListener("click",u),e.modalBackdrop.addEventListener("click",w),document.addEventListener("keydown",M)}function u(){e.modal.classList.remove("modal--is-open"),e.modalClose.removeEventListener("click",u),e.modalBackdrop.removeEventListener("click",w),document.removeEventListener("keydown",M)}function w(t){t.target===t.currentTarget&&u()}function M(t){t.code==="Escape"&&u()}let c=1,a,s=0,v,G=e.formSearch.querySelector(".search-form__input");async function I(){try{const t=await q();D(["All",...t]),A()}catch{l({message:"Try again later!"})}}async function B(){try{b();const t=await $(c);L(t.products),e.productList.addEventListener("click",r=>{Q(r)});const o=t.total;s=Math.ceil(o/d),P(c,s)}catch(t){l(t)}}async function h(){c+=1;let t;try{a?t=await S(a,c):t=await $(c),L(t.products);const o=t.total;s=Math.ceil(o/d),P(c,s)}catch(o){l(o)}}async function Q(t){try{if(!t.target.closest(".products__item"))return;const o=t.target.closest(".products__item").dataset.id,r=await O(`${o}`);F(r),j()}catch(o){l(o)}}function H(){e.formSearch.addEventListener("submit",async t=>{t.preventDefault(),a=t.target.searchValue.value.trim();try{if(!a)throw e.formSearch.reset(),new Error("Sorry, this name images is empty. Please try again!");a!==v&&(c=1,v=a),b();const o=await S(a,c),r=o.total;s=Math.ceil(r/d),r===0?N():(L(o.products),P(c,s))}catch(o){l(o)}})}function z(){e.clearBtn.addEventListener("click",t=>{t.preventDefault(),G.value="",a="",B()})}I();B();H();z();e.formSearch.reset();
//# sourceMappingURL=index.js.map
